name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0.0.2

    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Run tests
      run: make test
