name: CD

on:
  push:
    tags:
      - 'v*.*.*' # Enforce Semantic Versioning

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CD Environment
      uses: yetanalytics/actions/setup-env@v0.0.4

    - name: Cache Deps
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Run tests
      run: make test

    - name: Clean up
      run: make clean

    - name: Extract version
      id: version
      run: echo version=${GITHUB_REF#refs\/tags\/v} >> $GITHUB_OUTPUT

    - name: Build and deploy to Clojars
      uses: yetanalytics/action-deploy-clojars@v1
      with:
          artifact-id: 'pedestal-oidc'
          src-dirs: '["src/lib"]'
          resource-dirs: '[]'
          version: ${{ steps.version.outputs.version }}
          clojars-username: ${{ secrets.CLOJARS_USERNAME }}
          clojars-deploy-token: ${{ secrets.CLOJARS_PASSWORD }}

    - name: Craft Draft Release
      uses: softprops/action-gh-release@v1 # TODO: Update when new version is released 
      with:
        draft: true
        files: target/pedestal-oidc-${{ steps.version.outputs.version }}.jar
